name: JAVA CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: 'windows-latest'
    name: Test on Windows latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test With Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-version: wrapper
          build-root-directory: "."