name: JAVA CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: 'windows-latest'
    name: Test on Windows latest
    steps:
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Test With Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test